[package]
name = "romoulade"
version = "0.1.0"
authors = ["gcarq <egger.m@protonmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
bitflags = "2.8.0"
sdl2 = "^0.37"
tui = "0.12.0"
termion = "1.5.5"
unicode-width = "0.1.8"
backtrace = "0.3.51"

[profile.dev]
opt-level = 2
debug = true
rpath = false
lto = false
codegen-units = 8

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
codegen-units = 1