[package]
name = "romoulade"
version = "0.1.0"
authors = ["gcarq <egger.m@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
bitflags = "1.2.1"
sdl2 = "^0.34"

[profile.dev]
opt-level = 2
debug = true
rpath = false
lto = false
codegen-units = 8

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
codegen-units = 1