[package]
name = "romoulade"
version = "0.1.0"
authors = ["gcarq <egger.m@protonmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.9.0"
clap = { version = "4.5.30", features = ["derive"] }
eframe = { version = "0.31.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
egui = { version = "0.31.1", default-features = false }
egui_extras = { version = "0.31.1", default-features = false }
rfd = { version = "0.15.3", default-features = false, features = ["xdg-portal", "async-std"] }

[profile.dev]
opt-level = 2
debug = true
rpath = false
lto = false
codegen-units = 8

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
strip = true
codegen-units = 1
panic = "abort"