name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SDL
        run: sudo apt install libsdl2-dev libsdl2-2.0-0
      - name: Update Rust toolchain
        run: rustup update
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
